# Generated by Django 2.1.15 on 2020-07-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day1', models.IntegerField(default=0)),
                ('day2', models.IntegerField(default=0)),
                ('day3', models.IntegerField(default=0)),
            ],
        ),
    ]
