# Generated by Django 2.1.15 on 2020-07-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_simsale',
            fields=[
                ('cntn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('day1', models.IntegerField(blank=True, null=True)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('day3', models.IntegerField(blank=True, null=True)),
                ('day4', models.IntegerField(blank=True, null=True)),
                ('day5', models.IntegerField(blank=True, null=True)),
                ('day6', models.IntegerField(blank=True, null=True)),
                ('day7', models.IntegerField(blank=True, null=True)),
                ('day8', models.IntegerField(blank=True, null=True)),
                ('day9', models.IntegerField(blank=True, null=True)),
                ('day10', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
