# Generated by Django 2.1.15 on 2020-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200728_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaUserSimsale',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('cntn', models.CharField(max_length=50)),
                ('day1', models.IntegerField(blank=True, null=True)),
                ('day2', models.IntegerField(blank=True, null=True)),
                ('day3', models.IntegerField(blank=True, null=True)),
                ('day4', models.IntegerField(blank=True, null=True)),
                ('day5', models.IntegerField(blank=True, null=True)),
                ('day6', models.IntegerField(blank=True, null=True)),
                ('day7', models.IntegerField(blank=True, null=True)),
                ('day8', models.IntegerField(blank=True, null=True)),
                ('day9', models.IntegerField(blank=True, null=True)),
                ('day10', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'da_user_simsale',
                'managed': False,
            },
        ),
    ]
