# Generated by Django 3.2.11 on 2022-02-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datest_update_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datest',
            old_name='update_Dt',
            new_name='update_dt',
        ),
    ]
