# Generated by Django 2.1.15 on 2020-07-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200717_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBook',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'app_book',
                'managed': False,
            },
        ),
    ]
