# Generated by Django 3.2.11 on 2022-01-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dausersimsale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaUserSimsale',
        ),
    ]
