# Generated by Django 2.1.15 on 2020-07-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200723_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
