# Generated by Django 3.2.11 on 2022-02-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_update_dt_datest_update_dt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datest',
            table='da_zero',
        ),
    ]
