# Generated by Django 3.2.11 on 2022-02-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_datest_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datest',
            new_name='Dazero',
        ),
    ]
