# Generated by Django 2.1.15 on 2020-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
