# Generated by Django 2.1.15 on 2020-07-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
