# Generated by Django 2.1.15 on 2020-07-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
