# Generated by Django 2.1.15 on 2020-07-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dashboard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together={('no', 'app')},
        ),
    ]
