# Generated by Django 2.1.15 on 2020-07-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200727_1400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together=set(),
        ),
    ]
